### ISSUE TITLE
500 instead of 400 for "couldn't plan query: query validation errors"

### ISSUE THREAD

**Issue by xsoufiane** [apollographql/router#1511]
**Describe the bug**
The query:
```
mutation UpdatePj {
  updateProject(
     actions: [
       {setTrialUntil: {trialUntil: "2020-05-15T10:15:55+0100"}}
     ]
 ) {
   trialUntil
}
```
should fail with a 400 because actions is of type [ProjectSettingsUpdateAction!] and the input type ProjectSettingsUpdateAction has no field setTrialUntil. However, router returns 500 with **value retrieval failed: couldn't plan query: query validation errors: Field \"setTrialUntil\" is not defined by type \"ProjectSettingsUpdateAction\".**

**Expected behavior**
router response should be a 400.

**Comment by abernix** [comment]
agree!  thanks for opening this.

**Comment by abernix** [comment]
@xsoufiane Was this also fixed by https://github.com/apollographql/router/pull/1561?

**Comment by o0Ignition0o** [comment]
If it wasn't, could you pleazse provide me with part of a schema so I can try to reproduce it ?

**Comment by xsoufiane** [comment]
I run the test again, it's still failing with the same error 500 instead of 400. The schema we are using is something like this:
```
type Mutation {
  updateProject(actions: [[ProjectSettingsUpdateAction!]!], version: [Long!]): [ProjectProjection]
}
input ProjectSettingsUpdateAction {
  changeName: ChangeProjectSettingsName
  changeMessagesEnabled: ChangeProjectSettingsMessagesEnabled
}
input ChangeProjectSettingsName {
  name: String!
}
input ChangeProjectSettingsMessagesEnabled {
  messagesEnabled: Boolean!
}
```

**Comment by o0Ignition0o** [comment]
Hey @xsoufiane, I tried to reproduce it with this query:

```graphql
mutation UpdateProject($actions: [[ProjectSettingsUpdateAction!]!], $version: [LongInput!]) {
  updateProject(actions: $actions, version: $version) {
    name
  }
}
```

and these variables

```json
{
  "actions": [
    [
      {
        "changeMessagesEnabled": {
          "messagesEnabled": true
        },
        "changeName": {
          "name": "this is a new name"
        },
        "thisFieldDoesntExist": "no it does not"
      }
    ]
  ],
  "version": [
    {
      "beginning": 1234,
      "end": 5678
    }
  ]
}
```
against this schema:
```graphql

schema
  @core(feature: "https://specs.apollo.dev/core/v0.1")
  @core(feature: "https://specs.apollo.dev/join/v0.1") {
  query: Query
  mutation: Mutation
}

directive @core(feature: String!) repeatable on SCHEMA

directive @join__field(
  graph: join__Graph
  requires: join__FieldSet
  provides: join__FieldSet
) on FIELD_DEFINITION

directive @join__type(
  graph: join__Graph!
  key: join__FieldSet
) repeatable on OBJECT | INTERFACE

directive @join__owner(graph: join__Graph!) on OBJECT | INTERFACE

directive @join__graph(name: String!, url: String!) on ENUM_VALUE

scalar join__FieldSet

enum join__Graph {
  MYSERVICE @join__graph(name: "myservice", url: "http://somewhere")
}

type Query {
  myQuery: String
}

type Mutation {
  updateProject(
    actions: [[ProjectSettingsUpdateAction!]!]
    version: [LongInput!]
  ): [ProjectProjection]
}
input ProjectSettingsUpdateAction {
  changeName: ChangeProjectSettingsName
  changeMessagesEnabled: ChangeProjectSettingsMessagesEnabled
}

input LongInput {
  beginning: Int
  end: Int
}

type Long {
  beginning: Int
  end: Int
}
input ChangeProjectSettingsName {
  name: String!
}
input ChangeProjectSettingsMessagesEnabled {
  messagesEnabled: Boolean!
}
type ProjectProjection {
  key: String!
  name: String!
  version: Long!
}
```

And I can't reproduce it (notice `"thisFieldDoesntExist": "no it does not"` ).

Could you please share me
- the mutation
- the variables
- a working supergraph schema

The schema you mentioned in your comment isn't a supergraph schema, and the `Long` type isn't provided, and it cannot work as is because Long is used as an `input` and as a `type` at the same time :/ .

This would help me reproduce it!

**Comment by abernix** [comment]
@xsoufiane Any updates on this?

**Comment by xsoufiane** [comment]
thank u @abernix and @o0Ignition0o for your efforts, we have a public subgraph schema here https://github.com/commercetools/commercetools-api-reference/blob/main/api-specs/graphql/schema.sdl but it's just for a subgraph. In our case, we only have a subgraph now and the tests fail for fed v1. If this doesn't help, then I will try to reproduce the issue with a dummy supergraph fed v2 schema.

**Comment by xsoufiane** [comment]
I managed to reproduce the issue using this :) :
```
schema
  @link(url: "https://specs.apollo.dev/link/v1.0")
  @link(url: "https://specs.apollo.dev/join/v0.2", for: EXECUTION)
{
   mutation: Mutation
}

directive @join__field(graph: join__Graph!, requires: join__FieldSet, provides: join__FieldSet, type: String, external: Boolean, override: String, usedOverridden: Boolean) repeatable on FIELD_DEFINITION | INPUT_FIELD_DEFINITION

directive @join__graph(name: String!, url: String!) on ENUM_VALUE

directive @join__implements(graph: join__Graph!, interface: String!) repeatable on OBJECT | INTERFACE

directive @join__type(graph: join__Graph!, key: join__FieldSet, extension: Boolean! = false, resolvable: Boolean! = true) repeatable on OBJECT | INTERFACE | UNION | ENUM | INPUT_OBJECT | SCALAR

directive @link(url: String, as: String, for: link__Purpose, import: [link__Import]) repeatable on SCHEMA

scalar join__FieldSet

scalar link__Import

enum link__Purpose {
  """
  `SECURITY` features provide metadata necessary to securely resolve fields.
  """
  SECURITY

  """
  `EXECUTION` features provide metadata necessary for operation execution.
  """
  EXECUTION
}

enum join__Graph {
  SPHERE @join__graph(name: "sphere" url: "http://localhost:4001")
}

type Mutation @join__type(graph: SPHERE) {
  updateProject(actions: [[ProjectSettingsUpdateAction!]!]): [Project]
}

type Query @join__type(graph: SPHERE) {
  projects: [Project]
}

type Project {
  name: String
}

input ProjectSettingsUpdateAction {
  changeName: String
}
```
and the query is:
r#"
mutation UpdatePj {
  updateProject(
    actions: [
      {setTrialUntil: {trialUntil: "2020-05-15T10:15:55+0100"}}
    ]
  ) {
    name
  }
}
"#,

**Comment by garypen** [comment]
fixed by: https://github.com/apollographql/router/pull/1720
