### ISSUE TITLE
a __typename field at the Query level should receive a matching response

### ISSUE THREAD

**Issue by Geal** [apollographql/router#1922]
in https://github.com/apollographql/router/issues/1800#issuecomment-1263678302, a deferred query is done where the `__typename`
field is not added in the right response

**Comment by abernix** [comment]
@Geal Is https://github.com/apollographql/router/issues/1677 related to this?

**Comment by Geal** [comment]
That's likely yes

**Comment by Geal** [comment]
fixed by #2253

**Comment by BoD** [comment]
It looks like I still see the issue with `1.6.0` with a query of the form:

```graphql
query CanDeferFragmentsOnTheTopLevelQueryFieldQuery {
  __typename
  ...FragmentOnQuery @defer
}
fragment FragmentOnQuery on Query {
  computers {
    id
  }
}
```

Repro steps:

```shell
git clone git@github.com:apollographql/apollo-kotlin.git
cd apollo-kotlin
git checkout ed8a6ec9d95697545b6211decb518aa4a8fd6fee
# Install and run the subgraph
(cd tests/defer/router/subgraphs/computers && npm install && APOLLO_PORT=4001 npm start)&
# Run the router
path/to/router --supergraph tests/defer/router/simple-supergraph.graphqls &
# Query
curl --request POST     --header 'content-type: application/json'     --header 'accept: multipart/mixed; deferSpec=20220824, application/json'     --url 'http://127.0.0.1:4000/'     --data '{"query":"query CanDeferFragmentsOnTheTopLevelQueryFieldQuery {\n  __typename\n  ...FragmentOnQuery @defer\n}\n\nfragment FragmentOnQuery on Query {\n  computers {\n    id\n  }\n}"}'
```

Actual:
```
--graphql
content-type: application/json

{"data":null,"hasNext":true}
--graphql
content-type: application/json

{"hasNext":false,"incremental":[{"data":{"__typename":"Query","computers":[{"id":"Computer1"},{"id":"Computer2"}]},"path":[]}]}
--graphql--
```

Expected:
```
--graphql
content-type: application/json

{"data":{"__typename":"Query"},"hasNext":true}
--graphql
content-type: application/json

{"hasNext":false,"incremental":[{"data":{"computers":[{"id":"Computer1"},{"id":"Computer2"}]},"path":[]}]}
--graphql--
```

**Comment by bnjjj** [comment]
I'm able to reproduce it, I will investigate
