### ISSUE TITLE
default value for accept

### ISSUE THREAD

**Issue by xsoufiane** [apollographql/router#1990]
**Describe the solution you'd like**
With the change in https://github.com/apollographql/router/releases/tag/v1.0.0-alpha.1, we would need to ask our customers to add an **Accept** header which is very difficult because we have several and it would take a lot of time. What we would like to have is a default for this header so that we don't need to add the header.

**Describe alternatives you've considered**
For info, we tried:
```
supergraph:
  preview_defer_support: false
```
but it doesn't remove this requirement, we still get 406.

**Comment by abernix** [comment]
Fixed by #1995

**Comment by xsoufiane** [comment]
sorry to ask again but we are still experiencing the same issue with v1.2.1 and we are not sure why 🤔

**Comment by bnjjj** [comment]
I'll re-open the issue to let us check it on our side. How do you use it ? Do you set a wildcard header ? Or do you use it with curl with no accept header ?

**Comment by xsoufiane** [comment]
> I'll re-open the issue to let us check it on our side. How do you use it ? Do you set a wildcard header ? Or do you use it with curl with no accept header ?

thank you, as for us we don't add any accept header

**Comment by bnjjj** [comment]
Ok I was able to reproduce. A PR is coming
