### ISSUE TITLE
Unexpected query planner error with fragments

### ISSUE THREAD

**Issue by utay** [apollographql/router#3106]
The query planner fails unexpectedly with the following error:
    {
      "message": "value retrieval failed: router bridge error: the deno runtime raised an error: `request: couldn't receive response couldn't deserialize payload `5425825029548289619`: `deno: couldn't deserialize response : `Error(\"invalid neither null nor empty object: found Object {\\\"code\\\": String(\\\"QUERY_PLANNING_FAILED\\\"), \\\"exception\\\": Object {\\\"stacktrace\\\": Array [String(\\\"Cannot add selection of field \\\\\\\"NBAPlayer.id\\\\\\\" to selection set of parent type \\\\\\\"PlayerInterface\\\\\\\"\\\")]}}\", line: 0, column: 0)``.`",
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR"
      }
    },

<details>
<summary>Minimal schema to reproduce</summary>

```
type Query {
  nbaCard: NBACard!
}

interface PlayerInterface {
  id: Int!
  slug: String!
}

interface CardInterface {
  id: Int!
  player: PlayerInterface!
}

type NBAPlayer implements PlayerInterface {
  id: Int!
  slug: String!
}

type NBACard implements CardInterface {
  id: Int!
  player: NBAPlayer!
}
```
</details>

<details>
<summary>Query to reproduce</summary>

```
{
    nbaCard {
      ...Fragment1
      ...Fragment2
    }
}

fragment Fragment1 on NBACard {
  player {
    id
  }
}

fragment Fragment2 on CardInterface {
  ...Fragment2_bis
}

fragment Fragment2_bis on CardInterface {
  player {
    slug
    __typename
  }
}
```
</details>

Notes:
- There's only one subgraph involved in the schema and query 
- If I remove `__typename` from `Fragment2_bis` OR if I include `Fragment2_bis` directly in the query, it works
- I guess there's some sort of merging error because one player is of type `NBAPlayer` and the other of type `PlayerInterface`

Please let me know if I should report this issue on the JS repository (https://github.com/apollographql/federation) or feel free to do so!

**Comment by abernix** [comment]
Thanks for opening this!  This _might_ belong on the `federation` repository, but before I make the suggestion (or transfer it over there) — what version of the Router are you running?  That'll determine the version of Federation at play.

**Comment by utay** [comment]
Thanks! I run the router version 1.18.0

**Comment by abernix** [comment]
Thanks. That would be [Federation 2.4.2](https://www.apollographql.com/docs/router/federation-version-support/#support-table), then.  I think this is fixed in Federation 2.4.3.

Let me demonstrate how I've validated this.  First, at face-value, I'll point out the schema you shared is a _non-federated_ schema.  Running the Router or the Gateway requires a supergraph (which we also call a "core schema", sometimes).  I definitely believe you know that, but it's worth pointing out since we need that supergraph to run query planning on (even if there is just one subgraph).

If I assume the schema you provided is offered as an example of a single subgraph that you're (somewhere outside of this issue) composing into a supergraph (for example, [using `rover supergraph compose`](https://www.apollographql.com/docs/rover/commands/supergraphs/)), then it would yield a supergraph that looks like this:

```graphql
schema
  @link(url: "https://specs.apollo.dev/link/v1.0")
  @link(url: "https://specs.apollo.dev/join/v0.3", for: EXECUTION)
{
  query: Query
}

directive @join__enumValue(graph: join__Graph!) repeatable on ENUM_VALUE

directive @join__field(graph: join__Graph, requires: join__FieldSet, provides: join__FieldSet, type: String, external: Boolean, override: String, usedOverridden: Boolean) repeatable on FIELD_DEFINITION | INPUT_FIELD_DEFINITION

directive @join__graph(name: String!, url: String!) on ENUM_VALUE

directive @join__implements(graph: join__Graph!, interface: String!) repeatable on OBJECT | INTERFACE

directive @join__type(graph: join__Graph!, key: join__FieldSet, extension: Boolean! = false, resolvable: Boolean! = true, isInterfaceObject: Boolean! = false) repeatable on OBJECT | INTERFACE | UNION | ENUM | INPUT_OBJECT | SCALAR

directive @join__unionMember(graph: join__Graph!, member: String!) repeatable on UNION

directive @link(url: String, as: String, for: link__Purpose, import: [link__Import]) repeatable on SCHEMA

interface CardInterface
  @join__type(graph: A)
{
  id: Int!
  player: PlayerInterface!
}

scalar join__FieldSet

enum join__Graph {
  A @join__graph(name: "a", url: "https://films.example.com")
}

scalar link__Import

enum link__Purpose {
  """
  `SECURITY` features provide metadata necessary to securely resolve fields.
  """
  SECURITY

  """
  `EXECUTION` features provide metadata necessary for operation execution.
  """
  EXECUTION
}

type NBACard implements CardInterface
  @join__implements(graph: A, interface: "CardInterface")
  @join__type(graph: A)
{
  id: Int!
  player: NBAPlayer!
}

type NBAPlayer implements PlayerInterface
  @join__implements(graph: A, interface: "PlayerInterface")
  @join__type(graph: A)
{
  id: Int!
  slug: String!
}

interface PlayerInterface
  @join__type(graph: A)
{
  id: Int!
  slug: String!
}

type Query
  @join__type(graph: A)
{
  nbaCard: NBACard!
}
```

If I run this with Federation 2.4.2's query planner, I reliably reproduce the error you gave.  If I run it with Federation 2.4.3, then I get a valid query plan:

```graphql
QueryPlan {
  Fetch(service: "a") {
    {
      nbaCard {
        player {
          __typename
          slug
          id
        }
      }
    }
  },
}
```

We updated the query planner to v2.4.5 just this morning (via some amends commits to the automated PR opened by Renovate https://github.com/apollographql/router/pull/3107, so this should be fixed in the next release of the Router.  We're working on the details of that releasing timing right now.

**Comment by utay** [comment]
This all makes sense, thank you for the details @abernix! Looking forward to the next release :)

**Comment by utay** [comment]
We upgraded the router to 1.19.0 which fixed the bug mentioned above. However, with the same schema, the query planner still fails with:
    {
      "message": "value retrieval failed: router bridge error: the deno runtime raised an error: `request: couldn't receive response couldn't deserialize payload `12544047767499609238`: `deno: couldn't deserialize response : `Error(\"invalid neither null nor empty object: found Object {\\\"code\\\": String(\\\"QUERY_PLANNING_FAILED\\\"), \\\"exception\\\": Object {\\\"stacktrace\\\": Array [String(\\\"Cannot add selection of field \\\\\\\"NBAPlayer.id\\\\\\\" to selection set of parent type \\\\\\\"PlayerInterface\\\\\\\"\\\")]}}\", line: 0, column: 0)``.`",
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR"
      }
    }

for this query:
```
{
  nbaCard {
    ...Fragment1
    ...Fragment2
    ...Fragment3
  }
}

fragment Fragment1 on NBACard {
  player {
    id
  }
}

fragment Fragment2 on CardInterface {
  player {
    slug
  }
}

fragment Fragment3 on CardInterface {
  player {
    __typename
  }
}
```

**Comment by utay** [comment]
Hmm but `Fragment3` is defined, right? See the query above, it's not the same as the first one

**Comment by abernix** [comment]
Sorry, I forgot to scroll inside the codeblock.  It is there and it is defined. 😉
